//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightQuote.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int QuoteId { get; set; }
        public Nullable<int> VenderId { get; set; }
        public string ReferenceNo { get; set; }
        public string PickupLocation { get; set; }
        public string DeliveryLocation { get; set; }
        public System.DateTime ShipDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string Comments { get; set; }
    
        public virtual Vender Vender { get; set; }
    }
}
