//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightQuote.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vender
    {
        public Vender()
        {
            this.Quotes = new HashSet<Quote>();
        }
    
        public int VenderId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Quote> Quotes { get; set; }
    }
}
